services:
  - type: web
    name: paomauro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
